# Generated by Django 2.1.4 on 2018-12-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_key', models.CharField(max_length=100)),
                ('current_id', models.IntegerField()),
                ('pyplot_support', models.BooleanField(default=False)),
                ('sdk_support', models.BooleanField(default=False)),
                ('wizard_support', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
