# Generated by Django 2.1.4 on 2018-12-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0002_auto_20181213_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='pyplot_support',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motor',
            name='sdk_support',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motor',
            name='wizard_support',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
