# Generated by Django 2.1.4 on 2018-12-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0003_auto_20181213_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='qr_code',
            field=models.BinaryField(null=True),
        ),
    ]
